### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by ElSaam** [EdwinMindcraft/SeasonsAPI#4]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NoteBetterCore (notebetter-1.1.0.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  SeasonsPreLoader (SeasonsAPI-1.1.3a.jar)
  LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 12.5.2016 18:17
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:587)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:93)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:119)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
    at mod.mindcraft.seasons.Seasons.preInit(Seasons.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:561)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:584)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 32 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4ce7fffa from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 34 more
Caused by: java.lang.RuntimeException: Attempted to load class bmt for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
    ... 36 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2385080032 bytes (2274 MB) / 3087007744 bytes (2944 MB) up to 3087007744 bytes (2944 MB)
    JVM Flags: 2 total; -Xms3G -Xmx3G
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.1.1887 29 mods loaded, 29 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.1.1887-universal.jar) 
    UCH Forge{12.16.1.1887} [Minecraft Forge](forge-1.9-12.16.1.1887-universal.jar) 
    UCH abyssalcraft{1.9.1.1} [AbyssalCraft](AbyssalCraft-1.9-1.9.1.1.jar) 
    UCH basemetals{2.2.1} [Base Metals](BaseMetals_1.9-2.2.1.jar) 
    UCH Bloodmoon{1.2} [Bloodmoon](Bloodmoon-MC1.9-1.4.1.jar) 
    UCH craftelytra{1.0} [Craftable Elytra](CraftableElytra-1.0.jar) 
    UCH ctrades{1.3.2} [Custom Trades Mod](ctrades-1.3.2.jar) 
    UCH lootablebodies{2.0.0} [DrCyano's Lootable Bodies](CyanosLootableBodies_1.9-2.0.0.jar) 
    UCH grapple_hooks{1.0.8} [Grapple Hooks](Grapple Hooks-1.9-1.0.8.jar) 
    UCH hgp{Release} [Horizontal Glass Panes](hgp-1.9-1.0.2.jar) 
    UCH japta{1.4.1} [JAPTA](JAPTA-1.9-1.4.1.jar) 
    UCH jet_packs{1.0.0} [Just JetPacks](JustJetpacks-1.0.0.jar) 
    UCH malisiscore{1.9-3.0.6} [MalisisCore](malisiscore-1.9-3.0.6.jar) 
    UCH malisisdoors{1.9-4.0.1} [MalisisDoors](malisisdoors-1.9-4.0.1.jar) 
    UCH RadixCore{1.9-2.1.0} [RadixCore](RadixCore-1.9-2.1.0-universal.jar) 
    UCH MCA{1.9-5.1.2} [Minecraft Comes Alive](MCA-1.9-5.1.2-universal.jar) 
    UCH mfs{3.0.1} [Minecraft Flight Simulator](Minecraft Flight Simulator-1.9-3.0.1.jar) 
    UCH moarsigns{3.0.0} [MoarSigns](MoarSigns-1.9-3.0.0.jar) 
    UCH morefuelsmod-1.9{1.3.2} [§4§lMore Fuels Mod](morefuelsmod-1.9-v1.3.2.jar) 
    UCH moreplayermodels{1.9.0} [MorePlayerModels](MorePlayerModels_1.9.0beta%2801apr16%29.jar) 
    UCH notebetter{1.1.0} [NoteBetter](notebetter-1.1.0.jar) 
    UCE harvestcraft{1.9a} [Pam's HarvestCraft](Pam's HarvestCraft 1.9a.jar) 
    UCH parachutemod{1.4.1} [Parachute Mod](parachutemod-ng-1.9-1.4.1-396.jar) 
    UCH poweradvantage{2.1.0} [Power Advantage](PowerAdvantage_1.9.0-2.1.0.jar) 
    UCH RealisticTorches{1.5.4} [Realistic Torches](RealisticTorches-1.9-1.5.4.jar) 
    UCH rouletteores{1.2.21} [RouletteOres](RouletteOres-1.2.21.jar) 
    UCE seasonsapi{1.1.3a} [Seasons API](SeasonsAPI-1.1.3a.jar) 
    UCH worldedit{6.1.2} [WorldEdit](worldedit-forge-mc1.9-6.1.2-dist.jar) 
    Loaded coremods (and transformers): 
NoteBetterCore (notebetter-1.1.0.jar)
  com.github.soniex2.notebetter.asm.NoteBetterClassTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
SeasonsPreLoader (SeasonsAPI-1.1.3a.jar)
  mod.mindcraft.seasons.asm.Transformer
LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by EdwinMindcraft** [comment]
So... I might have found a way to fix it...

**Comment by EdwinMindcraft** [comment]
As well as a few other server side only bugs

**Comment by Emberion** [comment]
This also happens on 1.8.9, could you please back port the fix? I was using 1.0.3a.

**Comment by EdwinMindcraft** [comment]
I'll do it

**Comment by Emberion** [comment]
Thanks!

**Comment by EdwinMindcraft** [comment]
Posted 1.1.3b and 1.0.3b, bug is fixed in both

**Comment by Emberion** [comment]
Thanks so much!
